name: chatapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  location: ^5.0.3
  photo_view: ^0.14.0
  cloud_firestore: ^4.9.1
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  firebase_messaging: ^14.6.7
  firebase_in_app_messaging: ^0.7.3+5
  dots_indicator: ^3.0.0
  uni_links: ^0.5.1
  permission_handler: ^10.4.3
  package_info: ^2.0.2
  path_provider: ^2.1.1
  device_info: ^2.0.3
  flutter_screenutil: ^5.9.0
  share: ^2.0.4
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/