// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDImrI07O7SfVSXPECJLJC6-WutcNNEFY',
    appId: '1:34280743996:web:d0df692c440a0f8a35cf39',
    messagingSenderId: '34280743996',
    projectId: 'chatapp-f39e9',
    authDomain: 'chatapp-f39e9.firebaseapp.com',
    storageBucket: 'chatapp-f39e9.appspot.com',
    measurementId: 'G-9MDX6CRETH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHcmPahKibh8evTopyj6GTGv-TOW1y3A',
    appId: '1:34280743996:android:0f2aedb67d9be95d35cf39',
    messagingSenderId: '34280743996',
    projectId: 'chatapp-f39e9',
    storageBucket: 'chatapp-f39e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQS24YQIIV-JpJEfpOENYJDpbsRF8T2o',
    appId: '1:34280743996:ios:8e41f9831d75976335cf39',
    messagingSenderId: '34280743996',
    projectId: 'chatapp-f39e9',
    storageBucket: 'chatapp-f39e9.appspot.com',
    iosClientId: '34280743996-fkki033cfovcfm856qfuvh4cuge8l6ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
